pkg=libqgsttools-p1-touch
divert_dir="/var/lib/$pkg-diverted"

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" -o purge = "$1" ]; then
  for version in 1.0.0 1.0 1; do
    dpkg-divert --package "$pkg" --remove --rename \
      --divert \
      "$divert_dir"/libqgsttools_p.so.$version.diverted-$pkg \
      /usr/lib/__ARCH__/libqgsttools_p.so.$version
  done

  if [ -d "$divert_dir" ]; then
    rmdir "$divert_dir"
  fi
fi

#DEBHELPER#
