pkg=libqt5multimedia5-touch
divert_dir="/var/lib/$pkg-diverted"

if [ install = "$1" ]; then
  if [ ! -d "$divert_dir" ]; then
    mkdir -p "$divert_dir"
  fi

  for version in 5.2.1 5.2 5; do
    dpkg-divert --package "$pkg" --add --rename \
      --divert \
      "$divert_dir"/libQt5Multimedia.so.$version.diverted-$pkg \
      /usr/lib/__ARCH__/libQt5Multimedia.so.$version
  done
fi

#DEBHELPER#
