pkg=qtdeclarative5-qtmultimedia-touch-plugin
divert_dir="/var/lib/$pkg-diverted"

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" -o purge = "$1" ]; then
  for file in qmldir plugins.qmltypes Video.qml libdeclarative_multimedia.so;do
  dpkg-divert --package "$pkg" --remove --rename \
    --divert \
    "$divert_dir"/$file.diverted-$pkg \
    /usr/lib/__ARCH__/qt5/qml/QtMultimedia/$file
  done

  if [ -d "$divert_dir" ]; then
    rmdir "$divert_dir"
  fi
fi

#DEBHELPER#
