pkg=qtdeclarative5-qtmultimedia-touch-plugin
divert_dir="/var/lib/$pkg-diverted"

if [ install = "$1" ]; then
  if [ ! -d "$divert_dir" ]; then
    mkdir -p "$divert_dir"
  fi

  for file in qmldir plugins.qmltypes Video.qml libdeclarative_multimedia.so;do
  dpkg-divert --package "$pkg" --add --rename \
    --divert \
    "$divert_dir"/$file.diverted-$pkg \
    /usr/lib/__ARCH__/qt5/qml/QtMultimedia/$file
  done
fi

#DEBHELPER#
